### PR TITLE
WE-637 clarification from Jade more changes

### PR DESCRIPTION
**Pull request by emb03**
@z3cka Jade had changes from Renee's request (re menu)

### CODE REVIEW

**Comment by z3cka** [comment]
Okay, @comradeandy-ucla ready for a deployment

**Comment by emb03** [comment]
I don't think this has been deployed yet? We would like to put this on production today but are missing these changes.

**Comment by comradeandy-ucla** [comment]
You're going to have to give me more of a heads up than a Github mention. I'll deploy here in a minute.

**Comment by emb03** [comment]
:smirk:

**Comment by z3cka** [comment]
@comradeandy-ucla okay, maybe a jira ticket is in order to track deployments, especially with deployments to prod

**Comment by emb03** [comment]
Would you like an additional Jira other than the current one WS-637?

**Pull request merged**
